apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-comment-deployment
  labels:
    app: docker-k8s-comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-comment
  template:
    metadata:
      labels:
        app: docker-k8s-comment
    spec:
      containers:
        - name: docker-k8s-comment
          image: nisali1997/comments-data-service
          ports:
          - containerPort: 8083